# Generated by Django 3.2.8 on 2021-10-21 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonebook',
            name='address',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonebook',
            name='email',
            field=models.EmailField(default=None, max_length=100),
            preserve_default=False,
        ),
    ]
